sudo: false
language: scala
scala:
  - 2.12.8
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
install:
  - ". $HOME/.nvm/nvm.sh"
  - nvm install 9.4.0
  - nvm use 9.4.0
  - npm install jsdom
before_install:
  - git fetch --tag
jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt test
    - stage: release
      script: sbt ci-release
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
